### PR TITLE
Add in support for date_picker arg

### PR DESCRIPTION
**Pull request by jordanmaguire**
This just includes `as: :date_picker` for dates and datetimes. That's the best option we have for those two types in the template.

### CODE REVIEW

**Comment by jordanmaguire** [comment]
This is the final feature for 0.5.0!

**Comment by swebb** [comment]
:+1:

**Comment by osiro** [comment]
Awesome!!!

OOC: does it support only time? If no, I might be adding soon since I'll need only time for shifts on CV!

**Comment by swebb** [comment]
@osiro make sure you have a chat with @jordanmaguire about the problems he had with shift times in Tempo. In particular, shifts that start on one day and finish on the next (e.g., 9pm to 1am).

**Comment by jordanmaguire** [comment]
@osiro no specific support for time. Whatever simple_form spits out is what you'll get.

If you want a custom input for time put it in the rails_template and have the generator pass in the expected input name.

**Pull request merged**
